/*
 * This source file was generated by the Gradle 'init' task
 */
package com.detector;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class ApplicationTest {

    @Test
    void contextLoads( ) {
    }
}
